### ISSUE TITLE
getting "connection refused" when playing widget

### ISSUE THREAD

**Issue by guy-mograbi-at-gigaspaces** [CloudifySource/cloudify-widget#53]
Something probably failed on Java installation as I found this message on the machine. 

/root/gigaspaces-cloudify-2.3.0-ga/tools/cli/../../bin/setenv.sh: line 89: /root/jdk1.6.0_32/bin/java: No such file or directory

There are a couple of things we can do : 
1. Verify connection to cloudify management when we get a serverNode from pool using (/service/testrest), destroy if no answer
2. Same as #1 - but after machine setup is completed. 
3. Fix the machine setup script to fail properly when something goes wrong. (my guess it didn't).

**Comment by adamlavie** [comment]
Do you want me to look into it? Do you have the machine logs?
